# Generated by Django 4.2 on 2023-04-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100, unique=True)),
                ('food_description', models.TextField(blank=True, max_length=500)),
                ('food_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image_url', models.CharField(blank=True, max_length=200)),
                ('food_category', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
