# Generated by Django 4.2 on 2023-04-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='base64_image',
            field=models.CharField(blank=True, max_length=100000),
        ),
    ]
